### PR TITLE
added locale for FR

### PR DESCRIPTION
**Pull request by jonadem**

### CODE REVIEW

**Comment by tobihille** [comment]
Thanks for the contribution! :-)

**Comment by tobihille** [comment]
The version containing your PR (1.4) is now on fdroid :-)

**Comment by jonadem** [comment]
Awesome ! \o/

**Comment by oldakka** [comment]
How can a I help you? I want to translate to Spanish, I have a perfect grammar in native Spanish and Latin American Spanish.

**Comment by tobihille** [comment]
Hi @CarlosGitHub11. Thanks for your interest
I created a moment a go a manual that should help you: https://github.com/tobihille/SeniorLauncher/blob/master/CONTRIBUTING.md
If something is missing or if you have any questions please ask :-)

**Pull request merged**
